AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  Facet rest API

Parameters:
  COGNITO_JWKS_URL:
    Type: String
    Description: Cognito JWKS URL

Resources:
  API:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./main
      CodeUri: ./build/main.zip
      Runtime: go1.x
      Timeout: 15
      Environment:
        Variables:
          COGNITO_JWKS_URL: !Ref COGNITO_JWKS_URL
          SKIP_AUTHENTICATION: !Ref SKIP_AUTHENTICATION
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY